### ISSUE TITLE
Latest fortran pinned at version 4 but mpich requires 3

### ISSUE THREAD

**Issue by ChristopherHogan** [conda-forge/mpich-feedstock#33]
Issue:
I have a recipe that depends on `mpich` and also uses `compiler('fortran')`. On MacOS, the fortran compiler seems to be pinned at version `4`, while `mpich` requires version `3`:
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - libgfortran[version='>=4.0.0,<5.0.0.a0']
  - mpich=3.2 -> libgfortran[version='>=3.0.1,<4.0.0.a0']
```
Hopefully just a rerender is needed.

@conda-forge-admin, please rerender
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
N/A
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
    active environment : base
    active env location : /Users/travis/miniconda
            shell level : 1
       user config file : /Users/travis/.condarc
 populated config files : /Users/travis/.condarc
          conda version : 4.6.3
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       base environment : /Users/travis/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/travis/miniconda/pkgs
                          /Users/travis/.conda/pkgs
       envs directories : /Users/travis/miniconda/envs
                          /Users/travis/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.3 requests/2.21.0 CPython/3.7.1 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by conda-forge-linter** [comment]
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as requested, but nothing actually changed.

**Comment by ChristopherHogan** [comment]
Not sure why the error is different, but now I'm seeing
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - hdf5=[build=mpi_mpich_*] -> libgfortran[version='>=3.0.1,<4.0.0.a0']
  - libgfortran[version='>=4.0.0,<5.0.0.a0']
```
Here's the `meta.yaml`:
```yaml
{% set version = "1.8.1.dev" %}
{% set buildnumber = 0 %}

package:
  name: mpb
  version: {{version}}

source:
  git_url: https://github.com/NanoComp/mpb.git
  git_rev: master

build:
  number: {{buildnumber}}
  features:
    - nomkl

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - openblas
    - mpich
    - fftw
    - hdf5 * mpi_mpich_*
    - libctl >=4.1.4
  run:
    - openblas
    - fftw
    - hdf5 * mpi_mpich_*
    - libctl >=4.1.4
    - nomkl

test:
  commands:
    - test -f ${PREFIX}/lib/libmpb${SHLIB_EXT}

about:
  home: http:/github.com/NanoComp/mpb
  license: GPL-2.0
  license_file: COPYING
  summary: MIT Photonic-Bands - computation of photonic band structures in periodic media
  doc_url: http://mpb.readthedocs.io
  dev_url: https://github.com/NanoComp/mpb

```
